import { StyleSheet } from 'react-native';
import { fonts } from '../../constants/fonts';

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 2000,
  },
  modalContainer: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: fonts.MontserratSemiBold,
    marginBottom: 15,
    textAlign: 'center',
    color: 'rgba(70, 127, 127, 1)',
  },
  label: {
    fontSize: 14,
    marginBottom: 5,
    fontFamily: fonts.MontserratMedium,
    color: '#333',
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sign: {
    fontSize: 16,
    marginRight: 8,
    fontFamily: fonts.MontserratMedium,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(70, 127, 127, 0.3)',
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    color: '#333',
    fontFamily: fonts.MontserratMedium,
    backgroundColor: '#E6ECEF',
  },
  currency: {
    fontSize: 16,
    marginLeft: 8,
    color: '#333',
    fontFamily: fonts.MontserratMedium,
  },
  picker: {
    borderWidth: 1,
    borderColor: 'rgba(70, 127, 127, 0.3)',
    borderRadius: 8,
    backgroundColor: '#E6ECEF',
    marginBottom: 10,
    fontFamily: fonts.MontserratMedium,
  },
  dropDownContainer: {
    borderWidth: 1,
    borderColor: 'rgba(70, 127, 127, 0.3)',
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  pickerText: {
    fontSize: 14,
    color: '#333',
    fontFamily: fonts.MontserratRegular,
  },
  listItemContainer: {
    height: 30,
  },
  dateText: {
    fontSize: 14,
    color: '#666', // Сірий колір для меншої "активності"
    fontFamily: fonts.MontserratMedium,
    marginBottom: 10,
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#F5F5F5', // Легший фон, щоб відрізнити від інтерактивних полів
    borderWidth: 0, // Прибираємо рамку
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  cancelButton: {
    backgroundColor: '#FF4D4D',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
    alignItems: 'center',
    shadowColor: '#FF4D4D',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  addButton: {
    backgroundColor: 'rgba(70, 127, 127, 1)',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
    shadowColor: 'rgba(70, 127, 127, 1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: fonts.MontserratRegular,
  },
});
